<a href="https://colab.research.google.com/github/chetools/CVE2005/blob/main/DimensionalAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
#dimensional powers of kg, m, s
P = [1, -1, -2]
L = [0, 1, 0]
D = [0, 1, 0]
rho = [1, -3, 0]
mu = [1, -1, -1]
V = [0, 1, -1]

In [11]:
dim_matrix= np.c_[P, L, D, rho, mu, V].astype(float)

In [12]:
np.linalg.matrix_rank(dim_matrix)

3

array([[ 0,  1,  0],
       [ 1, -3,  1],
       [ 0,  0, -1]])

In [15]:
np.linalg.solve(np.c_[L, rho, V].astype(float), -np.array(D).astype(float))

array([-1.,  0., -0.])

In [16]:
np.linalg.solve(np.c_[L, rho, V].astype(float), -np.array(mu).astype(float))

array([-1., -1., -1.])

In [17]:
np.linalg.solve(np.c_[L, rho, V].astype(float), -np.array(P).astype(float))

array([ 0., -1., -2.])